Capitulo8/Capitulo1/Controllers/FabricantesController.cs
using Modelo.Cadastros;
using Servico.Cadastros;
using Servico.Tabelas;
using System.Net;
using System.Web.Mvc;

namespace Capitulo1.Controllers
{
    public class FabricantesController : Controller
    {
        //Declaração dos serviços dsponiveis para Produto

        private ProdutoServico produtoServico = new ProdutoServico();
        private CategoriaServico categoriaServico = new CategoriaServico();
        private FabricanteServico fabricanteServico = new FabricanteServico();



        //buscando eliminar a redudancia (mesmos codigos para obter o objeto) no codigo das actions details, Edit e Delete da 
        //exibição do produto, criaremos um metodo privado ObterVisaoProdutoPorId(int? id) chamada ao serviço que retornará 
        //o produto solicitado pelo usuário para exibição ja que esse codigo repetia-se nos GETS de details, Edit e Delete.

        private ActionResult ObterVisaoFabricantePorId(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Fabricante fabricante = fabricanteServico.ObterFabricantePorId((int)id);

            if (fabricante == null)
            {
                return HttpNotFound();
            }

            return View(fabricante);
        }



        // Com a implementação das action GET , nos restam agora as que respondem ao HTTP POST.Duas delas referem-se à atualização ou
        // inserção de um produto. Eelas são semelhantes. Desta maneira, vamos criar um método privado para estas requisições.
        // implementação  há a invocação ao método de serviço para gravar o produto, independente de ser atualização ou inserção
        private ActionResult GravarFabricante(Fabricante fabricante)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    fabricanteServico.GravarFabricante(fabricante);
                    return RedirectToAction("Index");
                }
                return View(fabricante);
            }
            catch
            {
                return View(fabricante);
            }
        }

        // POST: Fabricantes/Delete
        ////Esta será responsável por deletar os dados informados na visão de deletar.
        ////ACTION POST que  recebe os dados escolhidos pelo usuário para serem deletados.
        [HttpPost]        
        public ActionResult Delete(int id)
        {
            try
            {
                Fabricante fabricante = fabricanteServico.EliminarFabricantePorId(id);
                //criamos um valor associado à chave [Message].Na visão, será possível recuperar este valor
                TempData["Message"] = "Fabricante " + fabricante.Nome.ToUpper() + " foi removido!!!!";

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        //GET: Delete Fabricante
        //ACITION destinada a criação da visao pra escolha do item a ser deletado.
        public ActionResult Delete(int? id)
        {
            return ObterVisaoFabricantePorId(id);
        }


        //GET: Detalhhes da Fabricantes
        //Como não haverá interação com o usuário na visão a ser gerada, implementaremos apenas a action HTTP GET
        public ActionResult Details(int? id)
        {
            return ObterVisaoFabricantePorId(id);
        }


        //ACTION POST que recebe do modelo para edição e salvar a alteração..
        //Esta será responsável por receber os dados informados na visão no editar escolhido.
        //ACTION POST que  recebe os dados escolhidos pelo usuário para serem alterados.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Fabricante fabricante)
        {
            return GravarFabricante(fabricante);
        }


        //GET: Edit, acition responsavel pela visao do editar fabricantes.
        //ACTION GET de edição de dados no controlador. informar os dados a serem editados pelo id na visão.
        //action GET para ser gerada a visão de interação com o usuário.
        public ActionResult Edit(int? id)
        {
            return ObterVisaoFabricantePorId(id);
        }



        ////ACTION POST que recebe o modelo para inserção.
        ////Este será responsável por receber os dados informados na visão e pessistir.
        ////ACTION POST que  recebe os dados inseridos pelo usuário.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Fabricante fabricante)
        {
            return GravarFabricante(fabricante);
        }


        //GET: Criação da view de criar novo Fabricante
        //ACTION GET de inserção de dados no controlador. informar os dados na visão.
        //action GET para ser gerada a visão de interação com o usuário de inserção de novo fabricante.
        public ActionResult Create()
        {
            return View();
        }

        // GET: Fabricantes utilizada para criação da visao inicial index com a listagem de Fabricantes
        public ActionResult Index()
        {
            return View(fabricanteServico.ObterFabricantesClassificadosPorNome());
        }
    }
}

Capitulo8/Capitulo1/Views/Fabricantes/Create.cshtml
@model Modelo.Cadastros.Fabricante

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "NOVO FABRICANTE";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="panel panel-primary">
        <div class="panel-heading">
            NOVO FABRICANTE
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "Text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer panel-info">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Novo Fabricante" class="btn btn-danger" />
                @Html.ActionLink("Retornar para Listagem de FABRICANTES", "Index", null, new { @class = "btn btn-warning" })
            </div>
            <br />
            <br />
        </div>
    </div>
}

@section ScriptPage{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript">

        //primeira instrução, que requisita o método removeClass(), removerá a classe active de todo elemento<li> .
        //Já a segunda instrução, por estar usando um elementonomeado (veja o # antes do nome liFabricantes ),
        //adicionará a classe active ao elemento liFabricantes .
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liFabricantes').addClass("active");
        });
    </script>
}

Capitulo8/Capitulo1/Views/Fabricantes/Delete.cshtml
@model Modelo.Cadastros.Fabricante

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Visualizar FABRICANTE";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        FABRICANTE a ser DELETADO
    </div>
    <div class="panel-body">
        <div class="form-group">
            @Html.LabelFor(model => model.Nome)<br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-user"></i>
                </span>
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
            </div>
        </div>
    </div>


    <div class="panel-footer panel-info">
        <a href="#" class="btn btn-info" data-toggle="modal"
           data-target="#deleteConfirmationModal">Remover</a>
        @Html.ActionLink("Retornar para a listagem", "Index", null, new { @class = "btn btn-info" })
    </div>
</div>

<div class="modal fade" id="deleteConfirmationModal" tabindex="-1"
     role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">
                    Confirmação de exclusão do FABRICANTE
                </h4>
            </div>
            <div class="modal-body">
                <p>
                    Você está prestes a remover o Fabricante <strong> @Model.Nome.ToUpper()  </strong> do cadastro.
                </p>
                <p>
                    <strong>
                        Você está certo que deseja prosseguir?

                    </strong>
                </p>
                @using (Html.BeginForm("Delete", "Fabricantes", FormMethod.Post, new { @id = "delete-form", role = "form" }))
                {
                    @Html.HiddenFor(m => m.FabricanteId)
                    @Html.AntiForgeryToken()
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        onclick="$('#delete-form').submit();">
                    Sim, Desejo Excluir.
                </button>
                <button type="button" class="btn btn-primary"
                        data-dismiss="modal">
                    Não, Voltar a tela Anterior.
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Utilização do  Partial Views _PorFabricante.cshtml  Com isso, cria-se uma visão master-detail entre Fabricante e Produtos-->
@Html.Partial("~/Views/Produtos/_PorFabricante.cshtml", Model.Produtos.ToList()) <!--Partial View -->

@section ScriptPage {
    <script src="~/Scripts/jquery.validate.min.js">
    </script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js">
    </script>
    <script type="text/javascript">

        //primeira instrução, que requisita o método removeClass(), removerá a classe active de todo elemento<li> .
        //Já a segunda instrução, por estar usando um elementonomeado (veja o # antes do nome liFabricantes ),
        //adicionará a classe active ao elemento liFabricantes .
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liFabricantes').addClass("active");
        });
    </script>
}

Capitulo8/Capitulo1/Views/Fabricantes/Details.cshtml
@model Modelo.Cadastros.Fabricante

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Detalhes de FABRICANTE";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        Detalhes de um FABRICANTE
    </div>
    <div class="panel-body">
        <div class="form-group">
            @Html.LabelFor(model => model.Nome)
            <br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-globe"></i>
                </span>
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
            </div>
        </div>
    </div>
    <div class="panel-footer panel-info">
        @Html.ActionLink("Alterar", "Edit", new { id = Model.FabricanteId }, new { @class = "btn btn-info" })
        @Html.ActionLink("Voltar a listagem", "Index", null, new { @class = "btn btn-info" })
    </div>
</div>

 <!-- Utilização do  Partial Views _PorFabricante.cshtml  Com isso, cria-se uma visão master-detail entre Fabricante e Produtos-->
@Html.Partial("~/Views/Produtos/_PorFabricante.cshtml",Model.Produtos.ToList()) <!--Partial View -->

@section ScriptPage {
    <script src="~/Scripts/jquery.validate.min.js">
    </script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js">
    </script>
    <script type="text/javascript">

        //primeira instrução, que requisita o método removeClass(), removerá a classe active de todo elemento<li> .
        //Já a segunda instrução, por estar usando um elementonomeado (veja o # antes do nome liFabricantes ),
        //adicionará a classe active ao elemento liFabricantes .
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liFabricantes').addClass("active");
        });
    </script>
}

Capitulo8/Capitulo1/Views/Fabricantes/Edit.cshtml
@model Modelo.Cadastros.Fabricante

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Alterando um FABRICANTE";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-primary">
        <div class="panel-heading">
            Editar FABRICANTE
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.FabricanteId)
                <div class="form-group">
                    @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="panel-footer panel-info">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Salvar" class="btn btn-info" />
                    @Html.ActionLink("Lista de FABRICANTES", "Index", null, new { @class = "btn btn-warning" })
                </div>
                <br />
                <br />
            </div>
        </div>
    </div>
}

 <!-- Utilização do  Partial Views _PorFabricante.cshtml  Com isso, cria-se uma visão master-detail entre Fabricante e Produtos-->
@Html.Partial("~/Views/Produtos/_PorFabricante.cshtml", Model.Produtos.ToList()) <!--Partial View -->

@section ScriptPage {
    <script src="~/Scripts/jquery.validate.min.js">
    </script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js">
    </script>
    <script type="text/javascript">

        //primeira instrução, que requisita o método removeClass(), removerá a classe active de todo elemento<li> . 
        //Já a segunda instrução, por estar usando um elementonomeado (veja o # antes do nome liFabricantes ), 
        //adicionará a classe active ao elemento liFabricantes .
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liFabricantes').addClass("active");
        });
    </script>
}

Capitulo8/Capitulo1/Views/Fabricantes/Index.cshtml
@model IEnumerable<Modelo.Cadastros.Fabricante>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Lista de FABRICANTES";
}

@if (@TempData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"]
    </div>
}

<div class="panel panel-primary">
    <div class="panel-heading">
        FABRICANTES REGISTRADOS
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.FabricanteId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FabricanteId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.ActionLink("Alterar", "Edit", new { id = item.FabricanteId }) -
                            @Html.ActionLink("Detalhes", "Details", new { id = item.FabricanteId }) -
                            @Html.ActionLink("Apagar", "Delete", new { id = item.FabricanteId })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="panel-footer panel-info">
        @Html.ActionLink("NOVO FABRICANTE", "Create", null, new { @class = "btn btn-success" })
    </div>
</div>
@section styles    {
    <link href="@Url.Content("~/content/DataTables/css/dataTables.bootstrap.css")" rel="stylesheet" />
}

@section ScriptPage
    {
    <script src=" @Url.Content("~/scripts/DataTables/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/scripts/DataTables/dataTables.bootstrap.js")"></script>
    <script type="text/javascript">

            $(document).ready(function () {
                $('.table').dataTable();
            });

        //precisamos enviar para o método dataTable() a coluna pela qual a listagem será classificada,
        //de acordo com o código seguinte.O valor 1 refere- se à segunda coluna, e o "asc" significa ascendente/ crescente
        $('.table').dataTable({
            "order": [[1, "asc"]]
        });

        //primeira instrução, que requisita o método removeClass(), removerá a classe active de todo elemento<li> . 
        //Já a segunda instrução, por estar usando um elementonomeado (veja o # antes do nome liFabricantes ), 
        //adicionará a classe active ao elemento liFabricantes .

        $('li').removeClass("active");
        $('#liFabricantes').addClass("active");

    </script>
}