Capitulo8/Capitulo1/Areas/Seguranca/Controllers/AdminController.cs
using Capitulo1.Areas.Seguranca.Models;
using Capitulo1.Infraestrutura;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Capitulo1.Areas.Seguranca.Controllers
{
    public class AdminController : Controller
    {


        // GET: DETAILS criar a visao para usuario
        [Authorize]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Usuario usuario = GerenciadorUsuario.FindById(id);

            if (usuario == null)
            {
                return HttpNotFound();
            }

            return View(usuario);
        }


        // POST: DELETE  action que receberá estes dados, que enfim realizará a persistência deles na base de dados
        [Authorize]
        [HttpPost]
        public ActionResult Delete(Usuario usuario)
        {
            Usuario user = GerenciadorUsuario.FindById(usuario.Id);

            if (user != null)
            {
                IdentityResult result = GerenciadorUsuario.Delete(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return new HttpStatusCodeResult(
                    HttpStatusCode.BadRequest);
                }
            }
            else
            {
                return HttpNotFound();
            }
        }


        // GET: DEELETE criar a visao para usuario Deletar
        [Authorize]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Usuario usuario = GerenciadorUsuario.FindById(id);

            if (usuario == null)
            {
                return HttpNotFound();
            }

            return View(usuario);
        }


        // POST: EDIT  action que receberá estes dados, que enfim realizará a persistência deles na base de dados
        [Authorize]
        [HttpPost]
        public ActionResult Edit(UsuarioViewModel usuarioViewModel)
        {
            if (ModelState.IsValid)
            {
                Usuario usuario = GerenciadorUsuario.FindById(usuarioViewModel.Id);

                usuario.UserName = usuarioViewModel.Nome;
                usuario.Email = usuarioViewModel.Email;
                usuario.PasswordHash = GerenciadorUsuario.PasswordHasher.HashPassword(usuarioViewModel.Senha);

                IdentityResult result = GerenciadorUsuario.Update(usuario);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }

            return View(usuarioViewModel);
        }


        // GET: EDIT criar a visao para usuario Editar
        [Authorize]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(
                HttpStatusCode.BadRequest);
            }

            Usuario usuario = GerenciadorUsuario.FindById(id);

            if (usuario == null)
            {
                return HttpNotFound();
            }

            var usuarioViewModel = new UsuarioViewModel();

            usuarioViewModel.Id = usuario.Id;
            usuarioViewModel.Nome = usuario.UserName;
            usuarioViewModel.Email = usuario.Email;

            return View(usuarioViewModel);
        }


        // GET: CREATE criar a visao para usuario criar
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: CREATE  action que receberá estes dados, que enfim realizará a persistência deles na base de dados
        [Authorize]
        [HttpPost]
        public ActionResult Create(UsuarioViewModel model)
        {
            if (ModelState.IsValid)
            {
                Usuario user = new Usuario
                {
                    UserName = model.Nome,
                    Email = model.Email
                };

                IdentityResult result = GerenciadorUsuario.Create(user, model.Senha);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }

            return View(model);
        }


        //método específico (e privado) para o registro de possíveis erros ocorridos durante a tentativa de inserção de um usuário       
        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }


        // GET: Seguranca/Admin
        
        [Authorize(Roles = "Administradores")]
        public ActionResult Index()
        {
            return View(GerenciadorUsuario.Users);
        }

        
        private GerenciadorUsuario GerenciadorUsuario
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<GerenciadorUsuario>();
            }
        }
    }
}

Capitulo8/Capitulo1/Areas/Seguranca/Controllers/PapelAdminController.cs
using Capitulo1.Areas.Seguranca.Models;
using Capitulo1.Infraestrutura;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Capitulo1.Areas.Seguranca.Controllers
{
    public class PapelAdminController : Controller
    {

        //POST EDIT
        [HttpPost]
        public ActionResult Edit(PapelModificationModel model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.IdsParaAdicionar ??
                new string[] { })
                {
                    result = UserManager.AddToRole(userId, model.NomePapel);

                    if (!result.Succeeded)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                }

                foreach (string userId in model.IdsParaRemover ??
                new string[] { })
                {
                    result = UserManager.RemoveFromRole(userId, model.NomePapel);

                    if (!result.Succeeded)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                }

                return RedirectToAction("Index");
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }


        //GET EDIT
        public ActionResult Edit(string id)
        {
            Papel papel = RoleManager.FindById(id);
            string[] memberIDs = papel.Users.Select(x => x.UserId).ToArray();
            IEnumerable<Usuario> membros = UserManager.Users.Where(x => memberIDs.Any(y => y == x.Id));
            IEnumerable<Usuario> naoMembros = UserManager.Users.Except(membros);

            return View(new PapelEditModel
            {
                Papel = papel,
                Membros = membros,
                NaoMembros = naoMembros
            });
        }

        // GET: Seguranca/PapelAdmin cria visao de listagem dos papeis
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }


        //GET: Create Papeis/Roles
        public ActionResult Create()
        {
            return View();
        }


        //POST: Create Papeis/Roles
        [HttpPost]
        public ActionResult Create([Required]string nome)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = RoleManager.Create(new Papel(nome));

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }

            return View(nome);
        }



        //metodos de obter configuração e metodos auxiliares as actions
        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private GerenciadorUsuario UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<GerenciadorUsuario>();
            }
        }

        private GerenciadorPapel RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<GerenciadorPapel>();
            }
        }
    }
}

Capitulo8/Capitulo1/Views/Shared/_Layout.cshtml
@using Capitulo1.Infraestrutura
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0" charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" />
    @RenderSection("styles", false)
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="jumbotron text-center">
                <h1>
                    Desenvolvimento em ASP.NET MVC
                    <small class="text-danger">Utilizando o Bootstrap</small>
                </h1>
                <div style="text-align:right;">

                    @{
                        if (Html.GetAuthenticatedUser().ToString() != "")
                        {
                            @Html.GetAuthenticatedUser();
                            @Html.ActionLink(" - Sair", "Logout", "Account");
                        }
                        else
                        {
                            @Html.ActionLink("Acessar", "Login", "Account", new { area = "Seguranca" }, null);
                        }
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-3 col-md-3 bg-success">
            <ul class="nav nav-pills nav-stacked">

                @*<li id="liHome" role="presentation" class="active"><a href="#">Home</a></li>*@
                <li id="liHome" role="presentation" class="active">
                    @Html.ActionLink("HOME", "Index", "HOME")
                </li>
                <li id="liCategorias" role="presentation">
                    @Html.ActionLink("Categorias", "Index", "Categorias")
                </li>
                <li id="liFabricantes" role="presentation">
                    @Html.ActionLink("Fabricantes", "Index", "Fabricantes")
                </li>
                <li id="liProdutos" role="presentation">
                    @Html.ActionLink("Produtos", "Index", "Produtos")
                </li>
                <li id="liUsuarios" role="presentation">
                    @Html.ActionLink("Usuários", "Index", "Admin", new { area = "Seguranca" }, null)
                </li>
                <li id="liPapeis" role="presentation">
                    @Html.ActionLink("Papéis", "Index", "PapelAdmin", new { area = "Seguranca" }, null)
                </li>
            </ul>
        </div>
        <div class="col-xs-9 col-md-9">
            <br />
            @RenderBody()
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-xs-12 col-md-12 bg-danger">
            <small>Layout com Bootstrap</small>
        </div>
    </div>
    </div>
    <script src="@Url.Content("~/scripts/jquery-3.1.1.js")"></script>
    <script src="@Url.Content("~/scripts/bootstrap.js")"></script>
    @RenderSection("ScriptPage", false)
</body>
</html>